changelog-seen = 2

[llvm]
targets = "WebAssembly;X86"
experimental-targets = ""
static-libstdcpp = false

[build]
host = ["x86_64-unknown-haiku"]
target = ["x86_64-unknown-haiku", "wasm32-unknown-unknown"]
extended = true

[install]
prefix = "/boot/system"

[rust]
channel = "stable"
lld = true
rpath = false
deny-warnings = false

[target.x86_64-unknown-haiku]
cc = "x86_64-unknown-haiku-gcc"
cxx = "x86_64-unknown-haiku-g++"
ar = "x86_64-unknown-haiku-ar"
linker = "x86_64-unknown-haiku-gcc"

[dist]
missing-tools = true
compression-formats = ["xz"]
